### ISSUE TITLE
switch to exceptions for error handling (instead of statuses) + mention in README

### ISSUE THREAD

**Issue by slayoo** [numba-mpi/numba-mpi#108]

**Comment by slayoo** [comment]
see https://numba.pydata.org/numba-doc/dev/reference/pysupported.html#pysupported-exception-handling

**Comment by Delcior** [comment]
let's remember to double check use cases featuring numba threading layer

**Comment by slayoo** [comment]
Indeed, due to possible threading (i.e., MPI calls within Numba's `prange` loops), it seems impossible...
Closing.

Related:
- https://github.com/numba/numba/pull/2307
- https://github.com/numba/numba/issues/2811
