### ISSUE TITLE
Apply to NumFOCUS for a grant 

### ISSUE THREAD

**Issue by Delcior** [numba-mpi/numba-mpi#124]
- [x] add code of conduct
- [ ] clarify copyright ownership and transfer rules
- [ ] add GPL headers to every file!
- [x] apply for affiliation https://numfocus.typeform.com/to/VUPE35?typeform-source=numfocus.org (deadline - July 15th )
- [ ] apply for funding (for particular feature, documentation beef up, team meeting) https://numfocus.org/programs/small-development-grants

**Comment by slayoo** [comment]
@Delcior, code of conduct in place, so we can apply for the NumFocus affiliation now.
