### ISSUE TITLE
Guard against install on Python <3.8 or make package compatible with Python <3.8.

### ISSUE THREAD

**Issue by DManowitz** [numba-mpi/numba-mpi#134]
Version 0.40 and higher of this package rely on `importlib.metadata`, which is only present on Python 3.8 and later.  Thus, trying to import this package with Python <3.8 will give an error.  This package's `setup.py` also has no minimum Python version check, so this package will install without problem on older versions of Python.

As a result, please either add a check for a minimum compatible Python version, or require `importlib-metadata` package for older Python versions (which, admittedly, are EOL, but may still be found).

**Comment by slayoo** [comment]
Thank you @DManowitz!
Here's a PR requiring Python >= 3.8 in setup.py: https://github.com/numba-mpi/numba-mpi/pull/135
