### ISSUE TITLE
remove "njit" mentions from project metadata, README and code

### ISSUE THREAD

**Issue by slayoo** [numba-mpi/numba-mpi#144]
since Numba 0.59, the `@njit` decorator is the same as plain `@jit`, hence it might be misleading when we refer to `njit` in:
- https://github.com/numba-mpi/numba-mpi/blob/88c8ab856f7b3ccc07019637f91b8ce76e7456f1/README.md?plain=1#L17
- https://github.com/numba-mpi/numba-mpi/blob/88c8ab856f7b3ccc07019637f91b8ce76e7456f1/README.md?plain=1#L48
- https://github.com/numba-mpi/numba-mpi/blob/88c8ab856f7b3ccc07019637f91b8ce76e7456f1/setup.py#L24

Most of numba-mpi API functions are also defined with `@njit`, which perhaps is worth changing to `@jit(nopython=True)`?

**Comment by david-zwicker** [comment]
I agree that just using `@jit` might be cleaner, but I would then not add `nopython=True` since this now seems to be the default.

**Comment by slayoo** [comment]
@david-zwicker 

> I agree that just using `@jit` might be cleaner, but I would then not add `nopython=True` since this now seems to be the default.

Indeed. I'm just puzzled how to best cater to users of Numba < 0.59?
Anyhow, on CI, when we test for Python 3.8, pip picks `numba-0.58.1`, so we have it covered.
