### ISSUE TITLE
Add support for the reduce function

### ISSUE THREAD

**Issue by elyurn** [numba-mpi/numba-mpi#155]
Hello,

Would it be possible to implement `reduce`? 
Is it very different in the implementation than `allreduce`?

Thank you!

**Comment by slayoo** [comment]
Hello, thanks for your feedback on numba-mpi. IIUC, implementation of `reduce` should be possible in the same way as `allreduce` is implemented. Help welcome!

**Comment by Delcior** [comment]
Addresed in #157. Please confirm if this works in your usecase

**Comment by elyurn** [comment]
It works well, thank you very much. It also divide by 1.5 the execution time of my program!
Why isn't the operator a default argument as in `allreduce` though?
