### ISSUE TITLE
MPICH stopped working on CI for Python <3.10 (works for 3.10!)

### ISSUE THREAD

**Issue by slayoo** [numba-mpi/numba-mpi#69]
example: https://github.com/atmos-cloud-sim-uj/numba-mpi/actions/runs/3540947727

error:
```
A process has executed an operation involving a call
to the fork() system call to create a child process.

As a result, the libfabric EFA provider is operating in
a condition that could result in memory corruption or
other system errors.

For the libfabric EFA provider to work safely when fork()
is called, you will need to set the following environment
variable:
          RDMAV_FORK_SAFE

However, setting this environment variable can result in
signficant performance impact to your application due to
increased cost of memory registration.

You may want to check with your application vendor to see
if an application-level alternative (of not using fork)
exists.

Your job will now abort.
```
Tha CI jobs then timeouts after 6h

**Comment by slayoo** [comment]
in CI: temporarily excluding MPICH for Python <3.10 (keeping 3.10) on Linux
https://github.com/atmos-cloud-sim-uj/numba-mpi/pull/72

**Comment by slayoo** [comment]
well, this is clearly out of the scope of this project. Since we still keep MPICH for Python 3.10, let's close this one

**Comment by youyuanyi** [comment]
I also encountered this problem, how did you solve it

**Comment by youyuanyi** [comment]
I also encountered this problem, how did you solve it

**Comment by Delcior** [comment]
what is your python version, numba-mpi version and how to reproduce it?

**Comment by slayoo** [comment]
> I also encountered this problem, how did you solve it

We have not even tried to solve it - seems to be an issue on the intersection of Python and MPICH, but only for older Pythons.
We have just limited CI runs to Python >= 3.10 for MPICH.

Upgrading Python seems to be the way out.

**Comment by youyuanyi** [comment]
> > I also encountered this problem, how did you solve it
> 
> We have not even tried to solve it - seems to be an issue on the intersection of Python and MPICH, but only for older Pythons. We have just limited CI runs to Python >= 3.10 for MPICH.
> 
> Upgrading Python seems to be the way out.

Thank you!
