### ISSUE TITLE
submit a JOSS paper (please note ideas in this issue)

### ISSUE THREAD

**Issue by slayoo** [numba-mpi/numba-mpi#75]

**Comment by slayoo** [comment]
for the record, here's an examples MPI/Python-related JOSS paper: https://doi.org/10.21105/joss.01340

**Comment by slayoo** [comment]
- HDF5/MPI-IO

**Comment by david-zwicker** [comment]
I think it would be good to find an example problem where we can demonstrate that using `numba` with MPI yields much better performance. I guess we would need to compare it to pure `numba` (using multithreading?) and pure python using `mpi4py`.

**Comment by slayoo** [comment]
Thanks @david-zwicker 

Just a few thoughts to follow up:
- the original reason for starting with `numba-mpi` was as follows: we have implemented the `PyMPDATA` PDE-solver project (https://doi.org/10.21105/joss.03896) with the entirety of time-stepping logic embedded in `@njit`-ted code, thus using mpi4py there was simply impossible (so for some projects, using `numba-mpi` is not a matter of choice/performance, but rather the only viable option)
- in the context of PyMPDATA, in which multi-threading is handled by `numba.prange` calls (akin to OpenMP looping), we do not expect any performance improvement by switching to MPI parallelism over multiple threads. The reason is that the Numba-based multithreading implicitly leverages the availability of shared-memory access: reading from the shared mem is done without any barriers or communication. We intend to use `numba-mpi` there for enabling distributed-memory parallelism.
- JOSS papers are meant to be (very) short: 250-1000 words, so there is not that much space for a comprehensive performance/scaling analysis... but 
- the JOSS [review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html#functionality) does mention "Performance: If there are any performance claims of the software, have they been confirmed?"

We are planning a basic scaling analysis for PyMPDATA using both Numba-prange threading and `numba-mpi` for @Delcior's MSc thesis, so this will be a good input for the paper in the context of discussing performance.

**Comment by david-zwicker** [comment]
I completely agree! The JOSS paper should not show a comprehensive performance comparison, but I think a demonstration of the performance improvement would be nice! If you already planned that for the Master thesis then one could certainly reuse the figure.

**Comment by slayoo** [comment]
worth mentioning https://juliaparallel.org/MPI.jl/

**Comment by slayoo** [comment]
Just noting down that we have met last week with @xann16 and @Delcior to discuss this "issue". The key good news is that we have finally solved last week the puzzle of creating an example depicting usage of multi-threading+MPI using numba-mpi - a wrap up of @Delcior's project (kudos @Delcior, looking forward to a PR to [PyMPDATA-MPI](https://github.com/open-atmos/PyMPDATA)!). This will be worth mentioning in the numba-mpi paper. 

Discussing about the paper plans, we have also noted to consider [SoftwareX](https://www.softxjournal.com/) instead of JOSS (the reason being that - as of now - the former "counts" towards bibliographic points in Poland, while the latter not).

**Comment by david-zwicker** [comment]
Sounds great! I'm flexible in terms of journals, but I agree that an example would be great to have!

**Comment by slayoo** [comment]
Another update: over the last days, we've finally merged into PyMPDATA-MPI the multi-threading developments and relevant example code that depicts MPI+threading logic. There are new animations in the README file that highlight he two domain-decomposition schemes (MPI + threadnig): https://github.com/open-atmos/PyMPDATA-MPI

Small steps, but moving forward!

kudos @Delcior

**Comment by david-zwicker** [comment]
Great! If we decide to write something up, I can supply some details on how we use MPI in `py-pde` (which is basically trivial domain decomposition, but still).

**Comment by slayoo** [comment]
Closing as the paper was just submitted to arXiv and SoftwareX!
Kudos @Delcior, @xann16, @abulenok & @david-zwicker
Thanks!

**Comment by slayoo** [comment]
https://arxiv.org/abs/2407.13712
