### ISSUE TITLE
project logo (svg)

### ISSUE THREAD

**Issue by slayoo** [numba-mpi/numba-mpi#79]

**Comment by xann16** [comment]
@slayoo Played for a bit and it yielded that simple mashup of logos of both guilty parties :) Feel free to use it, dabble with it further or maliciously discard ;)
![numba-mpi](https://github.com/numba-mpi/numba-mpi/assets/34724539/4be2eaef-57ee-4ca3-85bd-eb52671f6464)

**Comment by slayoo** [comment]
@Delcior, @abulenok, @david-zwicker, we have a logo!
@xann16, thank you!!! 

I'll soon work on populating it within the Github repo, Github organisation, README, etc

**Comment by david-zwicker** [comment]
Look cool! Thanks for the effort!

**Comment by slayoo** [comment]
and here we go:

1. Organisation profile: 
![image](https://github.com/numba-mpi/numba-mpi/assets/89685/bfe9b692-e413-4ab2-ae6b-ed65a317d15b)

2. README:
![image](https://github.com/numba-mpi/numba-mpi/assets/89685/36dc0377-8305-4082-8bce-154cce543de7)

(should also soon propagate to PyPI where we use the README contents)

Thank you @xann16 !!!
