### ISSUE TITLE
optional parameters in send(), recv()

### ISSUE THREAD

**Issue by Konjkov** [numba-mpi/numba-mpi#83]
Hello!

Tag should be an optional parameter in send, recv functions with default value MPI.ANY_TAG which is -1 and source should be an optional parameter in recv function with default value MPI.ANY_SOURCE like in mpi4pi - https://mpi4py.readthedocs.io/en/stable/reference/mpi4py.MPI.Comm.html

Best, Vladimir.

**Comment by slayoo** [comment]
Thanks for reporting it, @Konjkov!

Here's a draft with `ANY_TAG` and `ANY_SOURCE` support in `recv()`: https://github.com/numba-mpi/numba-mpi/pull/84

Is `ANY_TAG` support in `send()` an `mpi4py` addition or is it part of the standard/C API?
I cannot find any mention of it at:
- https://www.open-mpi.org/doc/v4.0/man3/MPI_Send.3.php
- https://www.mpich.org/static/docs/v3.3/www3/MPI_Send.html

**Comment by Konjkov** [comment]
I'm sorry, ANY_TAG not support in send().

https://www.mpich.org/static/docs/v3.2/www3/MPI_Send.html

MPI_ERR_TAG
Invalid tag argument. Tags must be non-negative; tags in a receive (MPI_Recv, MPI_Irecv, MPI_Sendrecv, etc.) may also be MPI_ANY_TAG. The largest tag value is available through the the attribute MPI_TAG_UB.

**Comment by slayoo** [comment]
Indeed, MPICH seems not to support it, but `mpi4py` does have a default value of zero:
https://github.com/mpi4py/mpi4py/blob/master/src/mpi4py/MPI/Comm.pyx#L273

The question is, if we want to mimic `mpi4py` behavior here?

**Comment by Konjkov** [comment]
I have a small project ~10000 lines on python & numba. High-level code is easier to write on pure python, and low-level code on Numba. For pure python I use mpi4py and for numba try to use numba-mpi. It would be probably nice if the code was similar in both cases, although the differences are easily overcome.
For example numba_mpi.allreduce can`t handle **scalar type as recvobj**, but mpi4py provides with Comm-class functions with upper case first letter for sending buffer like objects like Numpy arrays and  with lower case first letter for sending generic data objects. https://info.gwdg.de/wiki/doku.php?id=wiki:hpc:mpi4py
It would be nice to support such a convention, otherwise one have to convert generic numba types to and from numpy arrays.

code example where I should create an numpy array of one element to receive sum of lengths of self.energy_list from all processes

```
import numba as nb
import numba_mpi as nb_mpi

energy_list_len = np.empty(1, dtype=np.int64)
nb_mpi.allreduce(len(self.energy_list), energy_list_len)

```

Best Vladimir.

**Comment by slayoo** [comment]
@Konjkov Just to confirm, the default values for `tag` and `source` are now featured in `numba-mpi` v0.30 available on both PyPI and conda-forge. Thank you for reporting it! Thanks @Delcior for help.

Let's track progress and discuss the `allreduce` issue at #88
