### ISSUE TITLE
request for MPI_Gather (DONE) and MPI_Allgather (DONE)

### ISSUE THREAD

**Issue by Konjkov** [numba-mpi/numba-mpi#98]
Hello numba-mpi developers

For my project https://github.com/Konjkov/pycasino/blob/main/pycasino/markovchain.py#L422
I need MPI_Gather function or mayby MPI_Allgather would be better.

Best Vladimir

**Comment by david-zwicker** [comment]
Thank you for raising this issue. I unfortunately currently don't have the time to implement this, but I'm happy to help integrating a pull request when you do your own attempt. I think a good example to start the implementation would be [our implementation of `allreduce`](https://github.com/numba-mpi/numba-mpi/blob/main/numba_mpi/api/allreduce.py).

**Comment by Konjkov** [comment]
Iit's okay, I can wait about a year until the development of the pseudopotential and periodic systems, as well as the Hartree-Fock calculations in my project, is completed.

**Comment by Delcior** [comment]
@Konjkov @david-zwicker  we will take a look at it

**Comment by Delcior** [comment]
@Konjkov @david-zwicker hey, together with @slayoo, we've drafted the implementation of MPI_Scatter and MPI_Gather. Please take a look https://github.com/numba-mpi/numba-mpi/pull/101

**Comment by slayoo** [comment]
@Konjkov we've just released `numba-mpi` 0.33 with support for gather and scatter included, please check if that helps for your use case, feedback very welcome!

**Comment by slayoo** [comment]
@Konjkov, here's a PR extending `numba-mpi` to cover `allgather` as well: https://github.com/numba-mpi/numba-mpi/pull/103

**Comment by slayoo** [comment]
@Konjkov #103 also merged and released. To try it, please install `numba-mpi` 0.34.
Closing this issue, please reopen if anything would be missing or not behaving as expected.
Thanks for reporting!
